spring.application.name=user-management-system
spring.profiles.active=db
#spring.profiles.active=memory
server.port=8080
# JWT Configuration
jwt.secret=YzJhMWE5NGY4Y2MwN2Q2MjM0ZjVhZjQ4NzY0ODNiNTA5MjQ2ZjQxYjQ3YzA5YmFmN2ZmOTRhNmRmMTNhNjg2Mw==
#jwt.expiration=3600000
jwt.expiration=300000

# ===============================
# Logging Configuration
# ===============================

# Root logging level
logging.level.root=INFO

# Application-specific logging
#logging.level.com.usermanagement=DEBUG

# Spring Framework logging
logging.level.org.springframework=INFO

# Hibernate SQL logging (optional)
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Log file
logging.file.name=logs/application.log

# Log pattern for console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Log pattern for file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Default Admin Configuration
app.admin.username=admin
app.admin.first-name=System
app.admin.last-name=Admin
app.admin.email=admin@gmail.com
app.admin.password=Admin@123
app.admin.role=ROLE_ADMIN